version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./dev-data:/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PATH=/data/database.sqlite

volumes:
  sqlite-data:
